version: '3'
services:
  service: 
    container_name: service
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - nestjs-redis
  redis:
    container_name: nestjs-redis
    image: "redis:alpine"
    restart: always
    ports:
      - 6379:6379
