version: '3'
services:
  api: 
    container_name: "nestjs-api"
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "7070:7070"
    restart: always
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    container_name: "nestjs-redis"
    restart: always
    ports:
      - 6379:6379
